CREATE USER manager WITH PASSWORD '12345';
GRANT CONNECT ON DATABASE orderManSys to "manager";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "manager";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "management" TO "manager";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "prepare" TO "manager";

CREATE USER storekeeper WITH PASSWORD '12345';
GRANT CONNECT ON DATABASE orderManSys to "storekeeper";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "store" TO "storekeeper";

CREATE USER purchaser WITH PASSWORD '12345';
GRANT CONNECT ON DATABASE orderManSys to "purchaser";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "purchaser";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "management" TO "purchaser";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "prepare" TO "purchaser";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "purchase" TO "purchaser";
