CREATE TABLE IF NOT EXISTS test_load (
Handle varchar(255),
Title varchar(255),
Body_HTML varchar(255),
Vendor varchar(255),
Type varchar(255),
Tags varchar(255),
Published varchar(255),
Option1_Name varchar(255),
Option1_Value varchar(255),
Option2_Name,
Option2_Value,
Option3_Name,
Option3_Value,
Variant_SKU,
Variant_Grams,
Variant_Inventory_Tracker,
Variant_Inventory_Qty,
Variant_Inventory_Policy,
Variant_Fulfillment_Service	,
Variant_Price	,
Variant_Compare_At_Price	,
Variant_Requires_Shipping	,
Variant_Taxable	,
Variant_Barcode	,
Image_Src	,
Image_Alt_Text	,
Gift_Card	,
SEO_Title	,
SEO_Description	,
Google_Shopping_Google_Product_Category	,
Google_Shopping_Gender	,
Google_Shopping_Age_Group	,
Google_Shopping_MPN	,
Google_Shopping_AdWords_Grouping
Google_Shopping_AdWords_Labels	,
Google_Shopping_Condition	,
Google_Shopping_Custom_Product	,
Google_Shopping_Custom_Label_0	,
Google_Shopping_Custom_Label_1	,
Google_Shopping_Custom_Label_2	,
Google_Shopping_Custom_Label_3	,
Google_Shopping_Custom_Label_4	,
Variant_Image	,
Variant_Weight_Unit
);
